from typing import Dict, List


PERMISSIONS: List[Dict[str, str]] = [
    {"code": "dashboard:read", "name": "查看概览", "resource": "dashboard", "action": "read"},
    {"code": "user:read", "name": "查看用户", "resource": "user", "action": "read"},
    {"code": "user:create", "name": "创建用户", "resource": "user", "action": "create"},
    {"code": "user:update", "name": "更新用户", "resource": "user", "action": "update"},
    {"code": "user:disable", "name": "启用/禁用用户", "resource": "user", "action": "disable"},
    {"code": "user:reset_password", "name": "重置密码", "resource": "user", "action": "reset_password"},
    {"code": "role:read", "name": "查看角色", "resource": "role", "action": "read"},
    {"code": "role:create", "name": "创建角色", "resource": "role", "action": "create"},
    {"code": "role:update", "name": "更新角色", "resource": "role", "action": "update"},
    {"code": "role:delete", "name": "删除角色", "resource": "role", "action": "delete"},
    {"code": "permission:read", "name": "查看权限点", "resource": "permission", "action": "read"},
    {"code": "project:read", "name": "查看项目", "resource": "project", "action": "read"},
    {"code": "project:update", "name": "更新项目", "resource": "project", "action": "update"},
    {"code": "project:delete", "name": "删除项目", "resource": "project", "action": "delete"},
    {"code": "project:export", "name": "导出项目", "resource": "project", "action": "export"},
    {"code": "task:read", "name": "查看任务", "resource": "task", "action": "read"},
    {"code": "task:retry", "name": "重试任务", "resource": "task", "action": "retry"},
    {"code": "task:cancel", "name": "取消任务", "resource": "task", "action": "cancel"},
    {"code": "task:log:read", "name": "查看任务日志", "resource": "task_log", "action": "read"},
    {"code": "asset:read", "name": "查看资产", "resource": "asset", "action": "read"},
    {"code": "asset:download", "name": "下载资产", "resource": "asset", "action": "download"},
    {"code": "asset:delete", "name": "删除资产", "resource": "asset", "action": "delete"},
    {"code": "billing:read", "name": "查看计费", "resource": "billing", "action": "read"},
    {"code": "billing:price:update", "name": "更新计费价格", "resource": "billing_price", "action": "update"},
    {"code": "organization:read", "name": "查看组织", "resource": "organization", "action": "read"},
    {"code": "organization:update", "name": "更新组织", "resource": "organization", "action": "update"},
    {"code": "system:read", "name": "查看系统状态", "resource": "system", "action": "read"},
    {"code": "audit:read", "name": "查看审计日志", "resource": "audit", "action": "read"},
]

ALL_PERMISSION_CODES = [permission["code"] for permission in PERMISSIONS]

ROLE_DEFINITIONS = {
    "super_admin": {
        "name": "超级管理员",
        "description": "拥有全部管理权限，不能被删除。",
        "permissions": ALL_PERMISSION_CODES,
        "system": True,
    },
    "admin": {
        "name": "系统管理员",
        "description": "管理用户、角色、项目和系统状态。",
        "permissions": [
            "dashboard:read",
            "user:read",
            "user:create",
            "user:update",
            "user:disable",
            "user:reset_password",
            "role:read",
            "role:create",
            "role:update",
            "permission:read",
            "project:read",
            "project:update",
            "project:delete",
            "project:export",
            "task:read",
            "task:retry",
            "task:cancel",
            "task:log:read",
            "asset:read",
            "asset:download",
            "asset:delete",
            "billing:read",
            "organization:read",
            "organization:update",
            "system:read",
            "audit:read",
        ],
        "system": True,
    },
    "operator": {
        "name": "内容运营",
        "description": "查看、下载和导出项目资产。",
        "permissions": [
            "dashboard:read",
            "project:read",
            "project:export",
            "task:read",
            "task:retry",
            "task:cancel",
            "asset:read",
            "asset:download",
            "system:read",
        ],
        "system": True,
    },
    "viewer": {
        "name": "只读查看者",
        "description": "只读查看项目和资产。",
        "permissions": ["dashboard:read", "project:read", "task:read", "asset:read", "system:read"],
        "system": True,
    },
}
